 "somehow manages to kiss themselves."
 "kisses themselves. How did they do that!?"
 "sets up for a kiss, but their lips somehow meet with their own face."
 "gives a big ol kiss to **#{target}**!"
 "attacks **#{target}** with a swarm of kisses!"
 "sends a kiss to **#{target}** via USPS. It never arrived..."
 "gives a big ol' kiss to **#{target}**!"
 "attacks **#{target}** with a swarm of kisses!"
 "creates unnecesary tension by kissing **#{target}**!"
 "lays down a big moist smooch towards **#{target}**!"
