All signs point to yes,
My sources say yes,
Hmm, I'd say no,
Absolutely not,
Absolutely,
Try again,
Sounds right to me,
No, not today,
Maybe in a few years,
Chances are good,
Chances aren't good,
Outlook good,
Outlook not good,
