 "nukes themselves!"
 "manages to drop their nuke on their own head! Bye bye..."
 "nukes themselves, for some reason."
 "unleashes the hellfire of a thousand suns onto **#{target}**!"
 "nukes the fuck out of **#{target}**!"
 "drops a fat man on **#{target}**!"
 "turns **#{target}** into the next fallout game!"
 "nukes **#{target}**!"
 "straight up nukes **#{target}**!"
 "consigns **#{target}** to total nuclear annihilation!"
 "made **#{target}** wish for a nuclear winter."
 "turned **#{target}** into the next Bikini Atoll!"