 "manages to vore themselves. Impressive!"
 "vores himself?"
 "chows down on his own arm!"
 "vores **#{target}**!"
 "glomps **#{target}** with their big wide mouth!"
 "glomps **#{target}** with their big wide mouth!"
 "attempts to vore **#{target}**! Unfortunately that's an impossible task and all they did was get **#{target}**'s arm wet."
 "starts devouring **#{target}**'s ass."
 "starts devouring **#{target}**'s ass."
 "frikin murders **#{target}** and eats the remains."
 "vores **#{target}**. \\*burp\\*."
 "swallows **#{target}** in one gulp! They were never seen again."
