 "yiffs themselves, somehow."
 "attempts to stage a yiffing, yet somehow manages to yiff themselves."
 "manages to dong themselves. Impressive!"
 "yiffs **#{target}** right in the mouth!"
 "yiffs **#{target}** right in the arse!"
 "sneaks up behind **#{target}** and yiffs them right in the arse!"
 "gets yiffy with **#{target}**!"
 "trades fluids with **#{target}**!"
 "does something entirely indescribable to **#{target}**..."
 "dicks **#{target}** in record speed!"
