 "hugs themselves, for some reason."
 "sets up for a hug, then somehow manages to hug themselves."
 "wraps their arms around themselves."
 "walks right up to **#{target}** and hugs them!"
 "sneaks up behind **#{target}** and hugs them!"
 "nuzzles up close to **#{target}** for a hug!"
 "gives a big 'ol flufferhug to **#{target}**!"
 "surprises **#{target}** with a warm hug!"
 "embraces with **#{target}**. How sweet!"
 "spreads the love to **#{target}** through a big 'ol hug!"
