 "gropes themselves?"
 "grops theiw own bulgy wulgy uwu owo uwu!!!!"
 "slaps their own balls?"
 "grops **#{target}**'s bulgy woolgy!"
 "gwabs **#{target}**'s buwlgy wulgy uwu owo uwu!!!!"
 "sexually assults **#{target}**"
 "grops **#{target}**'s bulgy woolgy!"
 "gwabs **#{target}**'s buwlgy wulgy uwu owo uwu!!!!"
 "grabs **#{target}** by the :b:ussy!"
 ", you may need to seriously reconsider your life choices if you're going to virtua-grope someone on a furry discord."