 "stabs themselves. I dont know what they expected..."
 "gets into a knife fight! They manage to end up with their own knife in their gut."
 "stabs themselves with a spoon. It isn't very effective..."
 "stabs **#{target}** right in the gut!"
 "sneaks up behind **#{target}** and stabs them in the back!"
 "gets into a knife fight with **#{target}**!"
 "gets cheeky with **#{target}**!"
 "stabs **#{target}** in an attempt to steal their yiff! :scream_cat:"
 "lodges their blade directly into **#{target}**!"
 "tries to stab **#{target}**, but ends up grabbing their own knife by the blade."
 "gives **#{target}** a friendly little eyepoke! Retina jelly, anyone?"
 "exercises their green thumb and plants a few knives into **#{target}**'s back!"
