 "shoots themselves!"
 "shoots themselves with a toy pistol; It wasn't very effective."
 "commits auto-shootification!"
 "shoots **#{target}**! Tragic."
 "gets into a knife fight with **#{target}**! Evidently, guns make great knives. "
 "performs advanced facial surgery on **#{target}** using a shotgun!"
 "shoots **#{target}** point blank with a nerf blaster! They are immediately gibbed into hundreds of pieces."
 "duels to the death with **#{target}**! There are no survivors..."
 "blasts **#{target}** right in their chest with a .22! It bounces right off."
 "dumps a pound of lead into **#{target}**!"
 "lays down the law with **#{target}**."
