 "pets their own head."
 "attempts to pet someone on the head, yet somehow manages to pet their own."
 "wasn't even trying to pet anyone, yet still ends up petting themselves."
 "pets **#{target}** on their head!"
 "gives **#{target}** pets!"
 "sneaks up behind **#{target}** and surprizes them with a swarm of petting!"
 "fuzzily pets **#{target}**!"
 "pets **#{target}**'s warm fuzzy fluff!"
 "pets **#{target}** like the animal they are."
